In [33]:
import torch
import torch.nn as nn

# Tensor - a matix or an array
# They carry derivatives under the hood

a = torch.ones(3, 5)
print(a)

# Stores gradients/derivatives for this tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [34]:
# sum() and mean()

sum = torch.sum(a, axis = 1)    # get sum of every row (is like going across the cols which is axis = 1)
print(sum)

tensor([5., 5., 5.])


In [35]:
# squeeze() and unsqueeze()

a = torch.ones(5, 1)
print(a.shape)
print(a)

torch.Size([5, 1])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [36]:
squeezed = torch.squeeze(a)
print(squeezed.shape)
print(squeezed)
# became a vector of size 5

torch.Size([5])
tensor([1., 1., 1., 1., 1.])


In [37]:
# use dim = 1, because we want to make the shape a 5 x 1 and 1 is the first index
unsqueezed = torch.unsqueeze(squeezed, dim=1)
print(unsqueezed.shape)
print(unsqueezed)

torch.Size([5, 1])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [38]:
# Neural Network Models

class MyModel(nn.Module):
    # Constructor
    def __init__(self):
        super().__init__()
        self.first_layer = nn.Linear(4, 6)
        self.second_layer = nn.Linear(6, 6)
        self.final_layer = nn.Linear(6, 2)

    # Forward - get_model_prediction(example_datapoint)
    def forward(self, x):
        first_layer_output = self.first_layer(x) # same as doing self.first_layer.forward(x)
        second_layer_output = self.second_layer(first_layer_output)
        final_layer_output = self.final_layer(second_layer_output)
        return final_layer_output
        # or just return self.final_layer(self.second_layer(self.first_layer(x)))

model = MyModel()

# 1 single data point, every data point needs 4 attributes, so matrix size is 1 x 4
example_datapoint = torch.randn(1, 4)
# this would give random output because initial weights are randomly initialized
print(model(example_datapoint))

# Need to train the model for some number of iterations

# THEN we can actually use the model and get useful predictions

tensor([[0.5655, 0.0042]], grad_fn=<AddmmBackward0>)
